export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const SET_CART_ITEM_QUANTITY = "SET_CART_ITEM_QUANTITY";
export const SET_CART = "SET_CART";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
export const USER_ORDERS_REQUEST = "USER_ORDERS_REQUEST";
export const USER_ORDERS_SUCCESS = "USER_ORDERS_SUCCESS";
export const USER_ORDERS_FAIL = "USER_ORDERS_FAIL";
export const ORDER_STATUS_UPDATE_REQUEST = "ORDER_STATUS_UPDATE_REQUEST";
export const ORDER_STATUS_UPDATE_SUCCESS = "ORDER_STATUS_UPDATE_SUCCESS";
export const ORDER_STATUS_UPDATE_FAIL = "ORDER_STATUS_UPDATE_FAIL";

export const REVIEWABLE_PRODUCTS_REQUEST = "REVIEWABLE_PRODUCTS_REQUEST";
export const REVIEWABLE_PRODUCTS_SUCCESS = "REVIEWABLE_PRODUCTS_SUCCESS";
export const REVIEWABLE_PRODUCTS_FAIL = "REVIEWABLE_PRODUCTS_FAIL";
export const REVIEW_SUBMIT_REQUEST = "REVIEW_SUBMIT_REQUEST";
export const REVIEW_SUBMIT_SUCCESS = "REVIEW_SUBMIT_SUCCESS";
export const REVIEW_SUBMIT_FAIL = "REVIEW_SUBMIT_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const ADMIN_PROFILE_REQUEST = "ADMIN_PROFILE_REQUEST";
export const ADMIN_PROFILE_SUCCESS = "ADMIN_PROFILE_SUCCESS";
export const ADMIN_PROFILE_FAIL = "ADMIN_PROFILE_FAIL";
export const ADMIN_PROFILE_UPDATE_REQUEST = "ADMIN_PROFILE_UPDATE_REQUEST";
export const ADMIN_PROFILE_UPDATE_SUCCESS = "ADMIN_PROFILE_UPDATE_SUCCESS";
export const ADMIN_PROFILE_UPDATE_FAIL = "ADMIN_PROFILE_UPDATE_FAIL";
